version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: mich55_db_user
      POSTGRES_PASSWORD: eddad4a2b2fe6e10633f415fc3bee598
      POSTGRES_DB: mich55_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mich55_db_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./flask_backend
    restart: unless-stopped
    env_file:
      - ./flask_backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./assets:/app/../assets
      - ./data.json:/app/../data.json
    ports:
      - "5002:5000"

  frontend:
    image: nginx:1.25-alpine
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    ports:
      - "8000:80"

volumes:
  db_data: 